%beamerPresentation.cls
\ProvidesClass{beamerPresentation}
\LoadClass{beamer}

\mode<presentation> {
\usetheme{CambridgeUS} %NICE
}

\usepackage{graphicx} % Allows including images
\usepackage{booktabs} % Allows the use of \toprule, \midrule and \bottomrule in tables
\usepackage{cite}

\usepackage{caption}
%\usepackage{subcaption}
\usepackage{graphicx}

\usepackage{transparent}
\usepackage{eso-pic}
